name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: '.'
          container_name: test
          connection_string: ${{ secrets.CONNECTION_STRING }}
          sas_token: ${{secrets.SAS_TOKEN}}
          extra_args: '--pattern *.tar.gz'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
