on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - uses: lauchacarro/Azure-Storage-Action@v1.1
      with:
        folder: '' # All files and subfolders found in the specified folder will be uploaded.
        connection-string: $CONNECTION_STRING
        public-access-policy: BlobContainer # BlobContainer | Blob | None
        blob-container-name: 'test'
